# Generated by Django 6.0.4 on 2026-04-28 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("microservice", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="flux",
            name="id",
        ),
        migrations.AddField(
            model_name="flux",
            name="name",
            field=models.CharField(default="", max_length=128),
        ),
        migrations.AlterField(
            model_name="flux",
            name="date_time",
            field=models.DateTimeField(
                primary_key=True, serialize=False, verbose_name="date time"
            ),
        ),
        migrations.AlterField(
            model_name="flux",
            name="flux",
            field=models.FloatField(default=0.0),
        ),
    ]
