# Generated by Django 6.0.4 on 2026-04-28 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("microservice", "0002_remove_flux_id_flux_name_alter_flux_date_time_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="flux",
            name="name",
        ),
    ]
