# Generated by Django 6.0.4 on 2026-04-28 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("microservice", "0004_flux_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="flux",
            name="name",
        ),
    ]
