# Generated by Django 6.0.4 on 2026-05-07 17:28

import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("microservice", "0006_flux_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="MyUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="", max_length=128)),
                ("age", models.IntegerField(default=18)),
                ("country", django_countries.fields.CountryField(max_length=2)),
            ],
        ),
    ]
